[package]
name = "prometheum"
version = "0.1.1"
edition = "2021"
authors = ["Michael <michaeljosephvaden03@gmail.com>"]
description = "Lightweight Game Engine with Rust"
readme = "CRATEREADME.md"
license-file = "LICENSE.md"
keywords = ["gamedev", "graphics", "opengl", "vulkan"]

[dependencies]
